---
apiVersion: v1
kind: Namespace
metadata:
  name: three-tier

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    app: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      imagePullSecrets:
      - name: my-dockerhub-secret
      containers:
      - name: frontend
        image: rnjt80/frontend:1.1.22
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://app.172.18.0.5.nip.io/api/tasks"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: three-tier
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: three-tier
  annotations:
    external-dns.kubernetes.io/hostname: app.172.18.0.5.nip.io
spec:
  rules:
  - host: app.172.18.0.5.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: frontend-service
            port:
              number: 3000
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: backend-service
            port:
              number: 3500
